# Generic Apache site configuration for Moodle running in Docker with PHP 8.4
ServerTokens Prod
ServerSignature Off

# Ensure PHP version is hidden at the server level
Header always unset X-Powered-By
Header unset X-Powered-By

<VirtualHost *:80>
    
    # Point to the new public directory for Mooodle 5.0+
    DocumentRoot /var/www/html/public

    # https://moodle.org/mod/forum/discuss.php?d=422393
    RewriteEngine On
    RewriteRule "(^|/)\.(?!well-known\/)" - [R=404,L]
    RewriteRule "(composer\.json)" - [R=404,L]
    RewriteRule "(\.lock)" - [R=404,L]
    RewriteRule "(\/environment.xml)" - [R=404,L]
    RewriteRule "(\/install.xml)" - [R=404,L]
    RewriteRule "(\/README)" - [R=404,L]
    RewriteRule "(\/readme)" - [R=404,L]
    RewriteRule "(\/moodle_readme)" - [R=404,L]
    RewriteRule "(\/upgrade\.txt)" - [R=404,L]
    RewriteRule "(\/(upgrade\.txt|UPGRADING\.md|UPGRADING\-CURRENT\.md))" - [R=404,L]
    RewriteRule "(phpunit\.xml\.dist)" - [R=404,L]
    RewriteRule "(\/tests\/behat\/)" - [R=404,L]
    RewriteRule "(\/fixtures\/)" - [R=404,L]
    RewriteRule "(\/lib\/classes\/)" - [R=404,L]

    # Log real IP not proxy
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    
    CustomLog /var/log/apache2/access.log combined env=!forwarded
    CustomLog /var/log/apache2/access.log proxy env=forwarded

    ErrorLog /var/log/apache2/moodle_error.log

    # --- Target the public directory and enable Path Info ---
    <Directory "/var/www/html/public">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        # Critical for routing styles.php and javascript.php slash arguments
        AcceptPathInfo On 
    </Directory>

    # Error Documents
    ErrorDocument 503 /503.html

</VirtualHost>
<VirtualHost *:443>
    
    # Point to the new public directory for Mooodle 5.0+
    DocumentRoot /var/www/html/public
    
    SSLEngine on
    SSLCertificateFile /etc/apache2/certs/ssl-cert.pem
    SSLCertificateKeyFile /etc/apache2/certs/ssl-cert.key

    # https://moodle.org/mod/forum/discuss.php?d=422393
    RewriteEngine On
    RewriteRule "(^|/)\.(?!well-known\/)" - [R=404,L]
    RewriteRule "(composer\.json)" - [R=404,L]
    RewriteRule "(\.lock)" - [R=404,L]
    RewriteRule "(\/environment.xml)" - [R=404,L]
    RewriteRule "(\/install.xml)" - [R=404,L]
    RewriteRule "(\/README)" - [R=404,L]
    RewriteRule "(\/readme)" - [R=404,L]
    RewriteRule "(\/moodle_readme)" - [R=404,L]
    RewriteRule "(\/upgrade\.txt)" - [R=404,L]
    RewriteRule "(\/(upgrade\.txt|UPGRADING\.md|UPGRADING\-CURRENT\.md))" - [R=404,L]
    RewriteRule "(phpunit\.xml\.dist)" - [R=404,L]
    RewriteRule "(\/tests\/behat\/)" - [R=404,L]
    RewriteRule "(\/fixtures\/)" - [R=404,L]
    RewriteRule "(\/lib\/classes\/)" - [R=404,L]
    
    # Log real IP not proxy
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    
    CustomLog /var/log/apache2/access.log combined env=!forwarded
    CustomLog /var/log/apache2/access.log proxy env=forwarded

    ErrorLog /var/log/apache2/moodle_error.log

    # --- Target the public directory and enable Path Info ---
    <Directory "/var/www/html/public">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        # Critical for routing styles.php and javascript.php slash arguments
        AcceptPathInfo On 
    </Directory>

    # Error Documents
    ErrorDocument 503 /503.html

</VirtualHost>
