# Generic Apache site configuration for Moodle running in Docker with PHP 8.4
ServerTokens Prod
ServerSignature Off

<VirtualHost *:80>
    
    # Point to the new public directory for Mooodle 5.0+
    DocumentRoot /var/www/html/public

    # https://moodle.org/mod/forum/discuss.php?d=422393
    RewriteEngine On
    RewriteRule "(\/vendor\/)" - [F]
    RewriteRule "(\/node_modules\/)" - [F]
    RewriteRule "(^|/)\.(?!well-known\/)" - [F]
    RewriteRule "(composer\.json)" - [F]
    RewriteRule "(\.lock)" - [F]
    RewriteRule "(\/environment.xml)" - [F]
    RewriteRule "(\/install.xml)" - [F]
    RewriteRule "(\/README)" - [F]
    RewriteRule "(\/readme)" - [F]
    RewriteRule "(\/moodle_readme)" - [F]
    RewriteRule "(\/upgrade\.txt)" - [F]
    RewriteRule "(\/(upgrade\.txt|UPGRADING\.md|UPGRADING\-CURRENT\.md))" - [F]
    RewriteRule "(phpunit\.xml\.dist)" - [F]
    RewriteRule "(\/tests\/behat\/)" - [F]
    RewriteRule "(\/fixtures\/)" - [F]

# Log real IP not proxy
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    
    CustomLog /var/log/apache2/access.log combined env=!forwarded
    CustomLog /var/log/apache2/access.log proxy env=forwarded

    ErrorLog /var/log/apache2/moodle_error.log

    # --- Target the public directory and enable Path Info ---
    <Directory "/var/www/html/public">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        # Critical for routing styles.php and javascript.php slash arguments
        AcceptPathInfo On 
    </Directory>

    # Error Documents
    ErrorDocument 503 /503.html

</VirtualHost>
